### ISSUE TITLE
What does out represent.

### ISSUE THREAD

**Issue by deepsurbhi8** [quanhua92/human-pose-estimation-opencv#18]
Hi, 
My question is: For a single image, we get the output of dimension (1*19*47*47) where what 1 and 19 represent is understood. But for a single image, what does the 47*47 matrix represents? Please reply!!

**Comment by quanhua92** [comment]
It should be the output of the final layer of the model. It depends on which model you are using

**Comment by deepsurbhi8** [comment]
I need to estimate the 19 points you marked in the body points. For body pose, it should be coordinates in 2D. But we are getting a matrix of 47 by 47 for each point, like for the nose. How is it working?

**Comment by quanhua92** [comment]
I have the code to parse the output at line 60 https://github.com/quanhua92/human-pose-estimation-opencv/blob/master/openpose.py#L60

**Comment by quanhua92** [comment]
You need to find the maximum value and calculate the position using the image width or height with the output size

**Comment by deepsurbhi8** [comment]
Yeah! I got it. Thank You!
