### ISSUE TITLE
Detect key points for legs image

### ISSUE THREAD

**Issue by omaraga12** [quanhua92/human-pose-estimation-opencv#19]
Hello, I was testing the project, it is so good, but the problema is that when I want to detect the keyt points of half body it does not detect, specially when it is legs, like this image:
![image](https://user-images.githubusercontent.com/64969223/217304796-74d6042d-fc21-43c2-91b7-56601f6fa20f.png)
Is there a way that it can detect the poses in this kind o images?
Thank you so much

**Comment by quanhua92** [comment]
Hi,
This repo is only a demonstration for using OpenCV to run the forward pass of a specific model. You should contact the model author to ask for your usecase.

**Comment by omaraga12** [comment]
Thank you
