### ISSUE TITLE
cannot connect to X server 

### ISSUE THREAD

**Issue by HARIHARAN1103** [quanhua92/human-pose-estimation-opencv#5]
I have tried this model on the google colab. 

!python openpose.py --input image5.jpg
:cannot connect to X server

please suggest the solution.

**Comment by quanhua92** [comment]
The `openpose.py` uses `cv.imshow('OpenPose using OpenCV', frame)` to show the frame image so it can't run on Colab. You need to use matplotlib pyplot to show the image. Here is the tutorial: https://matplotlib.org/users/image_tutorial.html
