### ISSUE TITLE
How to detect the pose of multiple people？

### ISSUE THREAD

**Issue by RandomFool123** [quanhua92/human-pose-estimation-opencv#6]
I tested your model in pictures of multiple people and found that it seems that it is not possible to detect multiple people at the same time. Then I found a annotation in your program 'Originally, we try to find all the local maximums. To simplify a sample we just find a global one. However, only a single pose at the same time can be detected this way.' So is this model suitable for multi-person pose detection?If it can, how can I improve it?

**Comment by quanhua92** [comment]
Hi,
The main purpose of this repo is to show how to use `MobileNet` model in OpenCV. Actually, there are already some repos that do the multi-person pose detection. You can search it on github. I will try to implement that when I have time.

**Comment by RandomFool123** [comment]
Thank you very much for your work, because the calculation of the multi-person attitude recognition method I know at present is very huge and time-consuming, so I hope to have a relatively fast and accurate method, and look forward to your updates in the future 👍
